Update work and about me section
abdulrahmanshr75/My-Portifolio pull request #1
Opened 2021-12-02 19:53 UTC by abdulrahmanshr75

- added the linters
- configured the site

2021-12-02 20:50 UTC, keneogu requested changes
Hi @abdulrahmanshr75 , 

Good job so far!

- Linters are working
- well structured codes

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-12-02 20:50 UTC, keneogu commented on index.html
> +      <div class="second-container">
Let's make use of the `<section>` semantic tag instead of the `<div>` tag.

2021-12-02 20:50 UTC, keneogu commented on index.html
> +              <a class="button2" href="#">Get My Resume</a>
Add styling  for all your buttons with the `hover` `pressed` properties

2021-12-02 20:50 UTC, keneogu commented on index.html
> +                <a class="button" href="#">See Project</a>
Add a styling for the buttons with `hover` `pressed` properties

2021-12-03 08:54 UTC, Rustamxon7 approved these changes
## Hi @abdulrahmanshr75  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://i.pinimg.com/originals/77/0e/b0/770eb057449582c44672b2d2d1cc39b6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 09:14 UTC, merged